language: node_js
node_js:
  - 'stable'

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run-script build:storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: master
